### ISSUE TITLE
Join server button does not work.

### ISSUE THREAD

**Issue by KK-Designs** [FlafyDev/spotify-listen-together#10]
The join server button does not work. When I click on join server, the modal closes and nothing happens, I see no prompt to enter the URL. HOw do I fix this?

**Comment by davimaiaa** [comment]
same here

**Comment by AnthonySPL** [comment]
Any ideas?

**Comment by 42willow** [comment]
Refer to the README
> ⚠️ Not working anymore ⚠️
I'm not using Spotify anymore so I have no real motivation to continue maintaining this project.

**Comment by onyx-nxt** [comment]
> Refer to the README
> 
> > ⚠️ Not working anymore ⚠️
> > I'm not using Spotify anymore so I have no real motivation to continue maintaining this project.

Closing the issue
